package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Car;
import org.mybatis.cdi.Mapper;

@Mapper
public interface CarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    int insert(Car record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.CAR
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    List<Car> selectAll();
}