package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Shop;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ShopMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    int insert(Shop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    Shop selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    List<Shop> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SHOP
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    int updateByPrimaryKey(Shop record);
}