package lt.vu.mybatis.model;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.DESCRIPTION
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.DESCRIPTION
     *
     * @return the value of PUBLIC.CAR.DESCRIPTION
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.DESCRIPTION
     *
     * @param description the value for PUBLIC.CAR.DESCRIPTION
     *
     * @mbg.generated Sun Apr 11 17:25:29 EEST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }
}